"""
App URL maps and native desktop launcher maps.
Separated from config.py for clarity and maintainability.
"""

# ── Web app URLs (opened with the default browser) ────────────────────
APP_URLS = {
    "youtube": "https://www.youtube.com",
    "yt": "https://www.youtube.com",
    "whatsapp": "https://web.whatsapp.com",
    "wa": "https://web.whatsapp.com",
    "chrome": "https://google.com",
    "google": "https://google.com",
    "browser": "https://google.com",
    "instagram": "https://instagram.com",
    "insta": "https://instagram.com",
    "spotify": "https://open.spotify.com",
    "telegram": "https://t.me",
    "facebook": "https://facebook.com",
    "fb": "https://facebook.com",
    "twitter": "https://twitter.com",
    "x": "https://x.com",
    "gmail": "https://mail.google.com",
    "maps": "https://maps.google.com",
    "google maps": "https://maps.google.com",
    "github": "https://github.com",
    "gitlab": "https://gitlab.com",
    "bitbucket": "https://bitbucket.com",
    "stackoverflow": "https://stackoverflow.com",
    "stack overflow": "https://stackoverflow.com",
    "reddit": "https://reddit.com",
    "news": "https://news.ycombinator.com",
    "hn": "https://news.ycombinator.com",
    "hacker news": "https://news.ycombinator.com",
    "linkedin": "https://linkedin.com",
    "medium": "https://medium.com",
    "notion": "https://notion.so",
    "figma": "https://figma.com",
    "dribbble": "https://dribbble.com",
    "behance": "https://behance.net",
    "deviantart": "https://deviantart.com",
    "pixiv": "https://pixiv.net",
    "twitch": "https://twitch.tv",
    "discord": "https://discord.com/app",
    "slack": "https://slack.com",
    "trello": "https://trello.com",
    "asana": "https://asana.com",
    "jira": "https://jira.atlassian.com",
    "confluence": "https://confluence.atlassian.com",
    "canva": "https://canva.com",
    "miro": "https://miro.com",
    "excalidraw": "https://excalidraw.com",
    "desmos": "https://desmos.com",
    "wolfram": "https://wolframalpha.com",
    "wolframalpha": "https://wolframalpha.com",
    "chatgpt": "https://chat.openai.com",
    "claude": "https://claude.ai",
    "gemini": "https://gemini.google.com",
    "copilot": "https://copilot.microsoft.com",
    "perplexity": "https://perplexity.ai",
    "midjourney": "https://midjourney.com",
    "stablediffusion": "https://stability.ai",
    "huggingface": "https://huggingface.co",
    "hf": "https://huggingface.co",
    "pypi": "https://pypi.org",
    "npm": "https://npmjs.com",
    "crates": "https://crates.io",
    "dockerhub": "https://hub.docker.com",
    "vercel": "https://vercel.com",
    "netlify": "https://netlify.com",
    "aws": "https://aws.amazon.com",
    "gcloud": "https://cloud.google.com",
    "azure": "https://azure.microsoft.com",
    "digitalocean": "https://digitalocean.com",
    "cloudflare": "https://cloudflare.com",
    "namecheap": "https://namecheap.com",
    "godaddy": "https://godaddy.com",
    "leetcode": "https://leetcode.com",
    "hackerrank": "https://hackerrank.com",
    "codeforces": "https://codeforces.com",
    "codewars": "https://codewars.com",
    "replit": "https://replit.com",
    "codepen": "https://codepen.io",
    "codesandbox": "https://codesandbox.io",
    "jsfiddle": "https://jsfiddle.net",
    "wikipedia": "https://wikipedia.org",
    "wiki": "https://wikipedia.org",
    "archive": "https://archive.org",
    "imdb": "https://imdb.com",
    "rotten tomatoes": "https://rottentomatoes.com",
    "goodreads": "https://goodreads.com",
    "amazon": "https://amazon.com",
    "ebay": "https://ebay.com",
    "aliexpress": "https://aliexpress.com",
    "newegg": "https://newegg.com",
    "bestbuy": "https://bestbuy.com",
    "walmart": "https://walmart.com",
    "target": "https://target.com",
    "costco": "https://costco.com",
}

# ── Native desktop app launchers ──────────────────────────────────────
# Linux: command lists executed directly
LINUX_APPS = {
    "calculator": ["gnome-calculator"],
    "settings": ["gnome-control-center"],
    "files": ["nautilus"],
    "file manager": ["nautilus"],
    "text editor": ["gedit"],
    "editor": ["gedit"],
    "terminal": ["xterm"],
    "kitty": ["kitty"],
    "alacritty": ["alacritty"],
    "wezterm": ["wezterm"],
    "tilix": ["tilix"],
    "konsole": ["konsole"],
    "gnome terminal": ["gnome-terminal"],
    "xfce4 terminal": ["xfce4-terminal"],
    "lxterminal": ["lxterminal"],
    "mate terminal": ["mate-terminal"],
    "terminology": ["terminology"],
    "yakuake": ["yakuake"],
    "dropdown terminal": ["yakuake"],
    "camera": ["snapshot"],
    "music": ["rhythmbox"],
    "code": ["code"],
    "vscode": ["code"],
    "firefox": ["firefox"],
    "chrome": ["google-chrome"],
    "browser": ["firefox"],
}

# Windows: executable names / URI schemes (opened via ShellExecute)
WINDOWS_APPS = {
    "calculator": ["calc.exe"],
    "calc": ["calc.exe"],
    "notepad": ["notepad.exe"],
    "text editor": ["notepad.exe"],
    "editor": ["notepad.exe"],
    "files": ["explorer.exe"],
    "file manager": ["explorer.exe"],
    "file explorer": ["explorer.exe"],
    "settings": ["ms-settings:"],
    "terminal": ["cmd.exe"],
    "cmd": ["cmd.exe"],
    "paint": ["mspaint.exe"],
    "camera": ["microsoft.windows.camera:"],
    "code": ["code"],
    "vscode": ["code"],
    "chrome": ["chrome"],
    "edge": ["msedge"],
    "spotify": ["spotify"],
    "firefox": ["firefox"],
}

# macOS: app names passed to `open -a`
MACOS_APPS = {
    "calculator": ["Calculator"],
    "settings": ["System Settings"],
    "files": ["Finder"],
    "file manager": ["Finder"],
    "text editor": ["TextEdit"],
    "editor": ["TextEdit"],
    "terminal": ["Terminal"],
    "camera": ["Photo Booth"],
    "music": ["Music"],
    "code": ["Visual Studio Code"],
    "vscode": ["Visual Studio Code"],
    "safari": ["Safari"],
}
